import { Box } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Contents from "../Components/Contents";
import MapCaller from "../Components/Map";
import PersonPinIcon from "@mui/icons-material/PersonPin";
// import Map from "../Components/Map";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Contents />
      </main>
    </div>
  );
}
